[tool.poetry]
name = "zelezobeton"
version = "0.0.3"
description = "Textová adventura."
license = "MIT"
authors = ["Michal Porteš <michalportes1@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/underground-lab/zelezobeton"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
]

[tool.poetry.dependencies]
python = "^3.7"
streamlit = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
selenium = "^4.1.0"
jsonschema = "^4.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
