[tool.poetry]
name = "Železo, beton"
version = "0.0.1"
description = "Textová adventura."
license = "MIT"
authors = ["Michal Porteš <michalportes1@gmail.com>"]
readme = "REAMDE.md"
homepage = "https://github.com/underground-lab/zelezobeton"
classifiers = [
    "Development Status :: 1 - Planning",
]

[tool.poetry.dependencies]
python = "^3.7"
streamlit = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
