[tool.poetry]
name = "zelezobeton"
version = "0.1.0"
description = "Textová adventura."
license = "MIT"
authors = ["Michal Porteš <michalportes1@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/underground-lab/zelezobeton"
classifiers = [
    "Development Status :: 3 - Alpha",
]

[tool.poetry.dependencies]
python = "^3.7"
streamlit = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
selenium = "^4.1.2"
jsonschema = "^4.4.0"
handpick = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
