[tool.poetry]
name = "zelezobeton"
version = "0.2.0"
description = "Textová adventura."
license = "MIT"
authors = ["Michal Porteš <michalportes1@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/underground-lab/zelezobeton"
classifiers = [
    "Development Status :: 3 - Alpha",
]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
selenium = "^4.1.2"
jsonschema = "^4.4.0"
handpick = "^0.10.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
